name = "rewrite-botnet-server"
main = "src/index.ts"
compatibility_date = "2024-11-22"

assets = { directory = "public" }

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "prod-bunnyai"
# database_id = "caa21c45-3688-405b-a725-7b5ab7b83f2f"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

# [vars]
